# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'LeetCodeProject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!
pod 'Moya', '~> 12.0'
#pod 'SwiftyJSON', '4.2.0'
pod 'ObjectMapper', '3.4.1'
pod 'SnapKit', '~> 4.0.0'
#pod 'SwiftOCR','1.1'
pod 'Kingfisher','4.10.1'
  # Pods for LeetCodeProject

  target 'LeetCodeProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LeetCodeProjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
